name: dentmaged

jumbo:
  title: Welcome!
  description: Welcome to my website! Here you will be able to see my projects, blog and more!

baseurl: "http://dentmaged.github.io"

github: http://github.com/dentmaged/dentmaged.github.io

version: v1.0.0

sass:
  sass_dir: _scss
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-mentions

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md